/**
 * MikroORM SQLite dialect configuration.
 *
 * Used by:
 * - The MikroORM CLI for `npm run schema:emit:sqlite` and `npm run schema:update:sqlite`
 * - The runtime config (`mikro-orm.config.ts`) when `DATABASE_URL` is NOT set
 * - Integration tests via `buildApp({ db: ':memory:' })`
 *
 * Entities are shared with the Postgres config — only the driver and
 * connection differ. Entity files must use only portable `p.*` types.
 *
 * Schema is managed by `orm.schema.update()` at app boot (INFRA-005).
 * No migration files exist — schema-generator handles DDL idempotently.
 *
 * @see skills/mikroorm-dual-dialect.md
 */

import { defineConfig } from '@mikro-orm/sqlite';
import { Organization } from './entities/Organization.js';
import { User } from './entities/User.js';
import { Project } from './entities/Project.js';
import { TestRun } from './entities/TestRun.js';
import { TestResult } from './entities/TestResult.js';
import { TestArtifact } from './entities/TestArtifact.js';
import { IngestIdempotencyKey } from './entities/IngestIdempotencyKey.js';
import { AiPipelineLog } from './entities/AiPipelineLog.js';

export default defineConfig({
  entities: [Organization, User, Project, TestRun, TestResult, TestArtifact, IngestIdempotencyKey, AiPipelineLog],

  /**
   * Better Auth manages its own tables — exclude them from schema generation.
   * CTRFHub's User entity exists only for ORM relationship mapping; the actual
   * DDL for user/session/account/verification/apikey is handled by Better Auth's
   * own migration tooling (`runMigrations()`).
   *
   * Organization is NOT skipped — it is a CTRFHub-owned table whose DDL is
   * generated by MikroORM's schema-generator (INFRA-005 pivot).
   *
   * @see docs/planning/database-design.md §4 (Better Auth note)
   */
  schemaGenerator: {
    skipTables: ['user', 'session', 'account', 'verification', 'apikey'],
  },

  /**
   * Default to an in-memory database for development/testing.
   * At runtime, `dbName` is overridden by `SQLITE_PATH`.
   */
  dbName: process.env['SQLITE_PATH'] ?? ':memory:',

  /** Enable debug logging in development */
  debug: process.env['NODE_ENV'] !== 'production',
});
